Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcProject_Lema.Models
{
    public class Employee
    {
        [Key]
        public int EmployeeID { get; set; }

        [Required(ErrorMessage = "Name is Required!")]
        [StringLength(30, ErrorMessage = "Name Must Be in 20 Character")]
        public string EmployeeName { get; set; }

        [Required(ErrorMessage = "Email Must be Required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Enter Employee Valid Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Cellphone No.")]
        [MaxLength(11, ErrorMessage = "Contact Number Must be greater than 11 Digit")]
        [MinLength(11, ErrorMessage = "Contact Number Can't be less than 11 Digit")]
        public string Phone { get; set; }
        public string Address { get; set; }
    }
}

Controllers/AppointMasterController.cs
using MvcProject_Lema.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MvcProject_Lema.Controllers
{
    public class AppointMasterController : Controller
    {
        // GET: AppointMaster
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Trainee
        public ActionResult Index()
        {
            return View(db.AppointMasters.ToList());
        }

        // GET: Trainee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppointMaster appointMaster = db.AppointMasters.Find(id);
            if (appointMaster == null)
            {
                return HttpNotFound();
            }
            return View(appointMaster);
        }
        public JsonResult AppointDetails(int id)
        {
            var appointDetail = db.AppointDetails.Where(o => o.AppointMasterId == id).AsEnumerable().Select(o => new { appointMasterId = o.AppointMasterId, serviceId = o.ServiceId, quantity = o.Quantity.ToString("dd-MM-yyyy"), price = o.Price });
            return Json(appointDetail, JsonRequestBehavior.AllowGet);
        }

        // GET: Trainee/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Trainee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppointMasterId,AppointDate,CustomerName,Image")] AppointMaster appointMaster)
        {
            if (ModelState.IsValid)
            {
                db.AppointMasters.Add(appointMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(appointMaster);
        }
        // GET: Trainee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppointMaster appointMaster = db.AppointMasters.Find(id);
            if (appointMaster == null)
            {
                return HttpNotFound();
            }
            return View(appointMaster);
        }

        // POST: Trainee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AppointMasterId,AppointDate,CustomerName,Image")] AppointMaster appointMaster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appointMaster);
        }

        // GET: Trainee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppointMaster appointMaster = db.AppointMasters.Find(id);
            if (appointMaster == null)
            {
                return HttpNotFound();
            }
            return View(appointMaster);
        }

        // POST: Trainee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AppointMaster appointMaster = db.AppointMasters.Find(id);
            db.AppointMasters.Remove(appointMaster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

Controllers/EmployeeController.cs
using MvcProject_Lema.Models;
using MvcProject_Lema.Models.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject_Lema.Controllers
{
    public class EmployeeController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Employee
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }

        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(EmployeeVM svm)
        {
            Employee s = new Employee();
            if (ModelState.IsValid)
            {
                s.EmployeeName = svm.EmployeeName;
                s.Email = svm.Email;
                s.Phone = svm.Phone;
                s.Address = svm.Address;

                db.Employees.Add(s);
                db.SaveChanges();
                return RedirectToAction("Index");


            }

            return PartialView("_SuppliersView", db.Employees.ToList());
        }
        public ActionResult Edit(int id)
        {
            EmployeeVM svm = new EmployeeVM();
            Employee s = db.Employees.Find(id);
            svm.EmployeeName = s.EmployeeName;
            svm.Email = s.Email;
            svm.Phone = s.Phone;
            svm.Address = s.Address;


            if (s == null)
            {
                return HttpNotFound();

            }

            return PartialView(svm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeVM svm, int id)
        {
            Employee s = new Employee();
            s = db.Employees.Find(id);
            if (ModelState.IsValid)
            {
                s.EmployeeName = svm.EmployeeName;
                s.Email = svm.Email;
                s.Phone = svm.Phone;
                s.Address = svm.Address;
                db.Employees.Add(s);
                db.Entry(s).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }




            return PartialView("_SuppliersView", db.Employees.ToList());


        }

        public ActionResult Delete(int id)
        {
            Employee s = db.Employees.Find(id);
            EmployeeVM svm = new EmployeeVM();

            svm.EmployeeName = s.EmployeeName;
            svm.Email = s.Email;
            svm.Phone = s.Phone;
            svm.Address = s.Address;
            return PartialView(svm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSupplier(int id)
        {
            Employee s = db.Employees.Find(id);
            if (s != null)
            {
                db.Employees.Remove(s);
                db.SaveChanges();
            }
            return RedirectToAction("Index");

        }


        public ActionResult Details(int id)
        {

            Employee s = db.Employees.Find(id);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);

        }

    }
}

Views/Shared/_AppointPartial.cshtml
<table class="table table-borderd table-hover table-responsive" id="appointDetailsServices">
</table>
<span id="chooseServiceError" style="color:red;">

</span>

Views/Shared/_EmployeesView.cshtml
@model IEnumerable<MvcProject_Lema.Models.Employee>

@{
    ViewBag.Title = "Index";
}



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a href="@Url.Action("Edit","Employee",new {id=item.EmployeeID })" class="editDialog btn btn-warning btn-sm">Edit</a>

                <a href="@Url.Action("Details","Employee",new {id=item.EmployeeID })" class="DetailsDialog btn btn-info btn-sm">Details</a>

                <a href="@Url.Action("Delete","Employee",new {id=item.EmployeeID })" class="DeleteDialog btn btn-danger btn-sm" data-id="@item.EmployeeID">Delete</a>
            </td>
        </tr>
    }

</table>

<script>
    $(document).ready(function () {

        $("#Add").click(function () {
            $("#Add-Modal").modal("show");
        });

        $("#Add").click(function (event) {
            event.preventDefault();
            $.get(this.href, function (response) {
                $(".divForAdd").html(response);

            });
            $("#Add-Modal").modal({
                backdrop: "static",
            }, 'show');
        });

    

        $(".editDialog").click(function (event) {
            event.preventDefault();
            var url = $(this).attr("href"); // Get the URL from the Edit button
            $.get(url, function (response) {
                $(".divForUpdate").html(response);
                $("#Edit-Modal").modal("show"); // Show the modal after loading content
            });
        });

        $(".DetailsDialog").click(function (event) {
            event.preventDefault();
            var url = $(this).attr("href"); // Get the URL from the Details button
            $.get(url, function (response) {
                $(".divForDetails").html(response);
                $("#Details-Modal").modal("show"); // Show the modal after loading content
            });
        });


        $(".DeleteDialog").click(function (event) {
            event.preventDefault();
            var url = $(this).attr("href"); // Get the URL from the Delete button
            $.get(url, function (response) {
                $(".divForDelete").html(response);
                $("#Delete-Modal").modal("show"); // Show the modal after loading content
            });
        });


    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Appoint", "Index", "Appoint", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Details", "Index", "AppointMaster", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Customer", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                 
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>